"""empty message

Revision ID: 1cc81ce64c05
Revises: 55016d701938
Create Date: 2016-03-03 14:26:03.234459

"""

# revision identifiers, used by Alembic.
revision = '1cc81ce64c05'
down_revision = '55016d701938'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product', sa.String(), nullable=False),
    sa.Column('short_description', sa.String(length=64), nullable=True),
    sa.Column('Long_description', sa.String(length=225), nullable=True),
    sa.Column('uploadPhotoes', sa.String(length=255), nullable=True),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('disabled', sa.Boolean(), nullable=True),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_timestamp'), 'comments', ['timestamp'], unique=False)
    op.drop_column(u'posts', 'price_html')
    op.drop_column(u'posts', 'Long_description_html')
    op.drop_column(u'posts', 'product_html')
    op.drop_column(u'posts', 'uploadPhotoes_html')
    op.drop_column(u'posts', 'short_description_html')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'posts', sa.Column('short_description_html', sa.VARCHAR(length=64), nullable=True))
    op.add_column(u'posts', sa.Column('uploadPhotoes_html', sa.VARCHAR(length=255), nullable=True))
    op.add_column(u'posts', sa.Column('product_html', sa.VARCHAR(), nullable=True))
    op.add_column(u'posts', sa.Column('Long_description_html', sa.VARCHAR(length=225), nullable=True))
    op.add_column(u'posts', sa.Column('price_html', sa.INTEGER(), nullable=True))
    op.drop_index(op.f('ix_comments_timestamp'), table_name='comments')
    op.drop_table('comments')
    ### end Alembic commands ###
